<<<<<<< HEAD
<Workspace Version="1.3.2.2480" X="260.77959375" Y="180.13279375" zoom="1.33823125" ScaleFactor="1" Name="Export Views to NavisWorks" Description="exports 3d views to NavisWorks" ID="a7fbed11-447a-4ff5-b991-9d92bb8ad357" Category="Data-Shapes.Export">
=======
<Workspace Version="1.3.1.1736" X="260.77959375" Y="180.13279375" zoom="1.33823125" ScaleFactor="1" Name="Export Views to NavisWorks" Description="exports 3d views to NavisWorks" ID="a7fbed11-447a-4ff5-b991-9d92bb8ad357" Category="Data-Shapes.Export">
>>>>>>> origin/master
  <NamespaceResolutionMap>
    <ClassMap partialName="String" resolvedName="DSCore.String" assemblyName="DSCoreNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="f2163450-72cc-465d-b4c2-8ac5184171fe" type="PythonNodeModels.PythonNode" nickname="Python Script" x="247.010979978237" y="44.0880453210161" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import*

clr.AddReference('RevitServices')
from RevitServices.Persistence import DocumentManager

doc = DocumentManager.Instance.CurrentDBDocument

if isinstance(IN[0],list):
	views = UnwrapElement(IN[0])
else: 
	views = [UnwrapElement(IN[0])]

prefix = IN[2]
for v in views:
	nop = NavisworksExportOptions()
	nop.ExportScope = NavisworksExportScope.View
	nop.ViewId = v.Id
	doc.Export(IN[1],prefix + v.Name,nop)

OUT = "Success"</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="4194f4bc-4019-4f8b-a17a-f48a919b7df2" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-23.1649051686695" y="-0.747255005440962" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="views" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="5fd49c12-4bd0-47ef-b999-d6a1a175021c" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-100.132170729088" y="81.2525394994328" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Directorypath" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="0d73e9a7-950d-4088-942b-50710fdea028" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="451.483530032646" y="42.5935353101342" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="OUT" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="c2b9a97d-44ca-44e4-b639-d7e6f5ee22a1" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-57.6492571818213" y="166.263724972796" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="prefix" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="f2163450-72cc-465d-b4c2-8ac5184171fe" start_index="0" end="0d73e9a7-950d-4088-942b-50710fdea028" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4194f4bc-4019-4f8b-a17a-f48a919b7df2" start_index="0" end="f2163450-72cc-465d-b4c2-8ac5184171fe" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5fd49c12-4bd0-47ef-b999-d6a1a175021c" start_index="0" end="f2163450-72cc-465d-b4c2-8ac5184171fe" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c2b9a97d-44ca-44e4-b639-d7e6f5ee22a1" start_index="0" end="f2163450-72cc-465d-b4c2-8ac5184171fe" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Aperçu en arrière-plan" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>