<Workspace Version="1.2.2.91" X="166.579648191145" Y="112.01551875" zoom="1.33823125" Name="GetLinkedElements.ByHostViewAndCategory" Description="Getting all linked elements in host view filtered by categories" ID="db023864-5b55-47fb-9ec7-4d10f1cd4fce" Category="Data-Shapes.Revit.Elements">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="710ffeee-8ce6-48ef-a6b1-7a301d94ffff" type="PythonNodeModels.PythonNode" nickname="Python Script" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="4">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <PortInfo index="3" default="False" />
      <Script>#Copyright (c) mostafa el ayoubi ,  2017
#Data-Shapes www.data-shapes.net , elayoubi.mostafa@gmail.com

import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import*
clr.AddReference('RevitServices')
from RevitServices.Persistence import DocumentManager
doc = DocumentManager.Instance.CurrentDBDocument
import System
from System.Collections.Generic import *

clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import*
doc = DocumentManager.Instance.CurrentDBDocument

#Inputs
if isinstance(IN[2],list):
	categories = IN[2]
else:
	categories = [UnwrapElement(IN[2])]
linkdoc = IN[1]
if isinstance(IN[0],list):
	views = UnwrapElement(IN[0])
else:
	views = [UnwrapElement(IN[0])]

collector = []

#getting project base point elevation
basepointfilter = ElementCategoryFilter(BuiltInCategory.OST_ProjectBasePoint)
basepoint = FilteredElementCollector(doc).WherePasses(basepointfilter).ToElements()
bpelevation = [b.ParametersMap.get_Item('Elev').AsDouble() for b in basepoint]

#Category filter
catfilter = []
for i in categories:
	catfilter.append(ElementCategoryFilter(System.Enum.ToObject(BuiltInCategory, int(str(i.Id)))))

catfilterlist = List[ElementFilter](catfilter)
filter = LogicalOrFilter(catfilterlist)

UIunit = Document.GetUnits(doc).GetFormatOptions(UnitType.UT_Length).DisplayUnits
level = []
for v in views:

	#creating a boundingbox for each view from it's crop box and view range
	bb = v.CropBox
	vr = v.GetViewRange()
	topclip = PlanViewPlane.TopClipPlane
	bottomclip = PlanViewPlane.BottomClipPlane
	cutclip = PlanViewPlane.CutPlane
	toplevel = (doc.GetElement(vr.GetLevelId(topclip)))
	topoffset = vr.GetOffset(topclip)
	cutlevel = (doc.GetElement(vr.GetLevelId(cutclip)))
	cutoffset = vr.GetOffset(cutclip)
	try:
		topZ = toplevel.Elevation + topoffset - bpelevation[0]
	except:
		topZ = cutlevel.Elevation + cutoffset - bpelevation[0]
	bottomlevel = (doc.GetElement(vr.GetLevelId(bottomclip)))
	bottomoffset = vr.GetOffset(bottomclip)
	try:
		bottomZ = bottomlevel.Elevation + bottomoffset - bpelevation[0]
	except :
		bottomZ = cutlevel.Elevation - bpelevation[0]
	min = bb.Min
	max = bb.Max
	newmin = XYZ(min.X,min.Y,bottomZ)
	newmax = XYZ(max.X,max.Y,topZ)
	ol = Outline(newmin,newmax)

	#combining boundingbox and category filters
	bbfilter = BoundingBoxIntersectsFilter(ol)
	andfilter = LogicalAndFilter(filter,bbfilter)

	#collecting elements
	collector.append(FilteredElementCollector(linkdoc).WherePasses(andfilter).ToElements())

OUT = collector</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="e6996528-9ced-4b7c-8d68-67a7ffeded03" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="447" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Elements" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="c76d240e-b780-424d-8d62-78db0f5acb8b" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-38" y="-18" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Linked Document" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="37ea98df-cc87-40b7-8b3b-e1d293217fa1" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-6" y="42" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="View(s)" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="9bb259f5-8fcf-40ad-95e3-01a739bc68e8" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-7" y="108" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Categories" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="12e38b39-c45a-4b49-a4ba-63274b14bc3f" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0.380195357756861" y="192.846280304693" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Refresh : bool = true" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="710ffeee-8ce6-48ef-a6b1-7a301d94ffff" start_index="0" end="e6996528-9ced-4b7c-8d68-67a7ffeded03" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c76d240e-b780-424d-8d62-78db0f5acb8b" start_index="0" end="710ffeee-8ce6-48ef-a6b1-7a301d94ffff" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="37ea98df-cc87-40b7-8b3b-e1d293217fa1" start_index="0" end="710ffeee-8ce6-48ef-a6b1-7a301d94ffff" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9bb259f5-8fcf-40ad-95e3-01a739bc68e8" start_index="0" end="710ffeee-8ce6-48ef-a6b1-7a301d94ffff" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="12e38b39-c45a-4b49-a4ba-63274b14bc3f" start_index="0" end="710ffeee-8ce6-48ef-a6b1-7a301d94ffff" end_index="3" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-22.4400730133057" eyeY="75.1917877197266" eyeZ="20.7231826782227" lookX="6.98445796966553" lookY="-11.2652797698975" lookZ="-35.3084754943848" upX="0.0169127732515335" upY="0.99619472026825" upZ="-0.085498996078968" />
  </Cameras>
</Workspace>