<Workspace Version="1.3.2.2480" X="183.515499107143" Y="216.014654464286" zoom="1.33823125" ScaleFactor="1" Name="RayBounce On Link Category" Description="Same functionality as raybounce but takes linked model elements into account" ID="0e68ecd9-e2b5-4875-a334-8680f2f6e836" Category="Data-Shapes.Revit.RayBounce">
  <NamespaceResolutionMap>
    <ClassMap partialName="RayBounce" resolvedName="Revit.References.RayBounce" assemblyName="RevitNodes.dll" />
    <ClassMap partialName="Vector" resolvedName="Autodesk.DesignScript.Geometry.Vector" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Category" resolvedName="Revit.Elements.Category" assemblyName="RevitNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="1852c0e0-e60d-41f6-baa1-ea95d023d199" type="PythonNodeModels.PythonNode" nickname="Python Script" x="238.967030708845" y="3.69229640136672" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="5">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <PortInfo index="3" default="False" />
      <PortInfo index="4" default="False" />
      <Script>#Copyright (c) mostafa el ayoubi
#Data-Shapes www.data-shapes.net 2016 elayoub.mostafa@gmail.com

import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import*

clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

clr.AddReference('RevitServices')
from RevitServices.Persistence import DocumentManager

import System
from System.Collections.Generic import*

doc = DocumentManager.Instance.CurrentDBDocument

def tolist(input):
	if isinstance(input,list):
		return input
	else:
		return [input]

#Document UI Units
UIunit = Document.GetUnits(doc).GetFormatOptions(UnitType.UT_Length).DisplayUnits

#Inputs : Points, Direction, 3D View
if isinstance(IN[0],list):
	points = [XYZ(UnitUtils.ConvertToInternalUnits(i.X,UIunit),UnitUtils.ConvertToInternalUnits(i.Y,UIunit),UnitUtils.ConvertToInternalUnits(i.Z,UIunit)) for i in IN[0]]
else:
	points = [XYZ(UnitUtils.ConvertToInternalUnits(IN[0].X,UIunit),UnitUtils.ConvertToInternalUnits(IN[0].Y,UIunit),UnitUtils.ConvertToInternalUnits(IN[0].Z,UIunit))]

direction = XYZ(IN[1].X,IN[1].Y,IN[1].Z)
view = UnwrapElement(IN[2])

ex = []
pts = []
elems = []
<<<<<<< HEAD
categories = tolist(IN[3])
=======
categories = IN[3]
>>>>>>> origin/master
catfilters = []
for i in categories:
	catfilters.append(ElementCategoryFilter(System.Enum.ToObject(BuiltInCategory, int(str(i.Id)))))
catfilterlist = List[ElementFilter](catfilters)
filter = LogicalOrFilter(catfilterlist)

ri = ReferenceIntersector(filter,FindReferenceTarget.All,view)
ri.FindReferencesInRevitLinks = True

for p in points:
	ref = ri.FindNearest(p,direction)
	if ref == None:
		pts.append(None)
		elems.append(None)
	else:
		refel = ref.GetReference()
		linkinstance = doc.GetElement(refel.ElementId)
		try:
			elem = linkinstance.GetLinkDocument().GetElement(refel.LinkedElementId)
			elems.append(elem)
			refp = ref.GetReference().GlobalPoint
			pts.append(Point.ByCoordinates(UnitUtils.ConvertFromInternalUnits(refp.X,UIunit),UnitUtils.ConvertFromInternalUnits(refp.Y,UIunit),UnitUtils.ConvertFromInternalUnits(refp.Z,UIunit)))
		except:
			if not IN[4]:
				elems.append(linkinstance)
				refp = ref.GetReference().GlobalPoint
				pts.append(Point.ByCoordinates(UnitUtils.ConvertFromInternalUnits(refp.X,UIunit),UnitUtils.ConvertFromInternalUnits(refp.Y,UIunit),UnitUtils.ConvertFromInternalUnits(refp.Z,UIunit)))
			else:
				pass

OUT = pts , elems</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="1ea1e62a-781b-4c6e-8f4a-66fd40b166e6" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="584.648816835122" y="4.26372497279522" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Points" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="548e91fe-f73f-4138-913e-eacfcfc5cdb5" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-42.5714285714286" y="-38.2857142857142" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Points : Point[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="9378bf08-940d-4bb1-91e6-ecebf9fb819b" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-50.5714285714285" y="35.4285714285715" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Direction : Vector" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="35ecaa62-f132-44d4-a796-f23816aeaa3d" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-44.6593564666579" y="103.582408549665" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="3D View : View3D" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="6677bae3-81fb-4c08-9c0f-0ec0293e3a36" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-66.9017379683602" y="181.121043968618" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Category : Category" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="80f56a7b-68cd-472e-99c3-98e3fbe65f5b" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="402.263930467922" y="8.91195467898393" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="x[0];&#xA;x[1];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="9080cf61-8449-4640-b6cf-ea82a5a793c1" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="579.538606062507" y="77.3188303591027" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Elements" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="526861dc-fc7e-4615-83fa-6422d035cca5" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-70.6271797995623" y="251.06673120637" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="BounceOnLinksOnly : bool = true" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="1852c0e0-e60d-41f6-baa1-ea95d023d199" start_index="0" end="80f56a7b-68cd-472e-99c3-98e3fbe65f5b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="548e91fe-f73f-4138-913e-eacfcfc5cdb5" start_index="0" end="1852c0e0-e60d-41f6-baa1-ea95d023d199" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9378bf08-940d-4bb1-91e6-ecebf9fb819b" start_index="0" end="1852c0e0-e60d-41f6-baa1-ea95d023d199" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="35ecaa62-f132-44d4-a796-f23816aeaa3d" start_index="0" end="1852c0e0-e60d-41f6-baa1-ea95d023d199" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6677bae3-81fb-4c08-9c0f-0ec0293e3a36" start_index="0" end="1852c0e0-e60d-41f6-baa1-ea95d023d199" end_index="3" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="80f56a7b-68cd-472e-99c3-98e3fbe65f5b" start_index="0" end="1ea1e62a-781b-4c6e-8f4a-66fd40b166e6" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="80f56a7b-68cd-472e-99c3-98e3fbe65f5b" start_index="1" end="9080cf61-8449-4640-b6cf-ea82a5a793c1" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="526861dc-fc7e-4615-83fa-6422d035cca5" start_index="0" end="1852c0e0-e60d-41f6-baa1-ea95d023d199" end_index="4" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
<<<<<<< HEAD
    <Camera Name="Background Preview" eyeX="305.457167867674" eyeY="34.366868491008" eyeZ="130.911215003852" lookX="-162.804327858195" lookY="16.0018581254794" lookZ="-112.686376484897" upX="0.240402532652065" upY="0.956304755963039" upZ="0.166396622612817" />
=======
    <Camera Name="Background Preview" eyeX="-22.6594775654312" eyeY="24.5477673625504" eyeZ="109.520808232917" lookX="22.6594775654312" lookY="-24.5477673625504" lookZ="-109.520808232917" upX="0" upY="1" upZ="0" />
>>>>>>> origin/master
  </Cameras>
</Workspace>