<Workspace Version="1.2.1.3083" X="348.515499107143" Y="211.014654464286" zoom="1.33823125" Name="RayBounce On Link Category" Description="Same functionality as raybounce but takes linked model elements into account" ID="0e68ecd9-e2b5-4875-a334-8680f2f6e836" Category="Data-Shapes.Revit.RayBounce">
  <NamespaceResolutionMap>
    <ClassMap partialName="RayBounce" resolvedName="Revit.References.RayBounce" assemblyName="RevitNodes.dll" />
    <ClassMap partialName="Vector" resolvedName="Autodesk.DesignScript.Geometry.Vector" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Category" resolvedName="Revit.Elements.Category" assemblyName="RevitNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="1852c0e0-e60d-41f6-baa1-ea95d023d199" type="PythonNodeModels.PythonNode" nickname="Python Script" x="239.714285714286" y="4.43955140680765" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="4">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <PortInfo index="3" default="False" />
      <Script>#Copyright (c) mostafa el ayoubi
#Node-mode www.data-shapes.net 2016 elayoub.mostafa@gmail.com

import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import*

clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

clr.AddReference('RevitServices')
from RevitServices.Persistence import DocumentManager

import System

doc = DocumentManager.Instance.CurrentDBDocument

#Document UI Units


UIunit = Document.GetUnits(doc).GetFormatOptions(UnitType.UT_Length).DisplayUnits

#Inputs : Points, Direction, 3D View
if isinstance(IN[0],list):
	points = [XYZ(UnitUtils.ConvertToInternalUnits(i.X,UIunit),UnitUtils.ConvertToInternalUnits(i.Y,UIunit),UnitUtils.ConvertToInternalUnits(i.Z,UIunit)) for i in IN[0]]
else:
	points = [XYZ(UnitUtils.ConvertToInternalUnits(IN[0].X,UIunit),UnitUtils.ConvertToInternalUnits(IN[0].Y,UIunit),UnitUtils.ConvertToInternalUnits(IN[0].Z,UIunit))]

direction = XYZ(IN[1].X,IN[1].Y,IN[1].Z)
view = UnwrapElement(IN[2])

ex = []
pts = []
elems = []
_category = IN[3]
filter = ElementCategoryFilter(System.Enum.ToObject(BuiltInCategory, _category.Id))
ri = ReferenceIntersector(filter,FindReferenceTarget.All,view)
ri.FindReferencesInRevitLinks = True

for p in points:
	ref = ri.FindNearest(p,direction)
	el = doc.GetElement(ri.GetTargetElementIds())
	if ref == None:
		pts.append(None)
		elems.append(None)
	else:
		refp = ref.GetReference().GlobalPoint
		pts.append(Point.ByCoordinates(UnitUtils.ConvertFromInternalUnits(refp.X,UIunit),UnitUtils.ConvertFromInternalUnits(refp.Y,UIunit),UnitUtils.ConvertFromInternalUnits(refp.Z,UIunit)))
		elems.append(el)


OUT = pts , elems</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="1ea1e62a-781b-4c6e-8f4a-66fd40b166e6" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="584.648816835122" y="4.26372497279522" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Points" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="548e91fe-f73f-4138-913e-eacfcfc5cdb5" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-42.5714285714286" y="-38.2857142857142" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Points : Point[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="9378bf08-940d-4bb1-91e6-ecebf9fb819b" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-50.5714285714285" y="35.4285714285715" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Direction : Vector" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="35ecaa62-f132-44d4-a796-f23816aeaa3d" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-44.6593564666579" y="103.582408549665" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="3D View : View3D" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="6677bae3-81fb-4c08-9c0f-0ec0293e3a36" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-66.9017379683602" y="181.121043968618" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Category : Category" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="80f56a7b-68cd-472e-99c3-98e3fbe65f5b" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="402.263930467922" y="8.91195467898393" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="x[0];&#xA;x[1];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="9080cf61-8449-4640-b6cf-ea82a5a793c1" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="579.538606062507" y="77.3188303591027" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Elements" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="1852c0e0-e60d-41f6-baa1-ea95d023d199" start_index="0" end="80f56a7b-68cd-472e-99c3-98e3fbe65f5b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="548e91fe-f73f-4138-913e-eacfcfc5cdb5" start_index="0" end="1852c0e0-e60d-41f6-baa1-ea95d023d199" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9378bf08-940d-4bb1-91e6-ecebf9fb819b" start_index="0" end="1852c0e0-e60d-41f6-baa1-ea95d023d199" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="35ecaa62-f132-44d4-a796-f23816aeaa3d" start_index="0" end="1852c0e0-e60d-41f6-baa1-ea95d023d199" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6677bae3-81fb-4c08-9c0f-0ec0293e3a36" start_index="0" end="1852c0e0-e60d-41f6-baa1-ea95d023d199" end_index="3" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="80f56a7b-68cd-472e-99c3-98e3fbe65f5b" start_index="0" end="1ea1e62a-781b-4c6e-8f4a-66fd40b166e6" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="80f56a7b-68cd-472e-99c3-98e3fbe65f5b" start_index="1" end="9080cf61-8449-4640-b6cf-ea82a5a793c1" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="7.45157357662174" eyeY="16.6031416839228" eyeZ="9.96334080577824" lookX="-9.91837907196055" lookY="-14.4157846842041" lookZ="-13.0147234323051" upX="-0.293860556357939" upY="0.874619707139397" upZ="-0.385598679069833" />
  </Cameras>
</Workspace>