<Workspace Version="1.3.3.4111" X="194" Y="169" zoom="1" ScaleFactor="1" Name="SlabShape.AddPoints" Description="Add points to slab shape" ID="8c355a8a-2fc0-4275-bfba-c9758a3a01a1" Category="Data-Shapes.Revit.Floors">
  <NamespaceResolutionMap>
    <ClassMap partialName="PolyCurve" resolvedName="Autodesk.DesignScript.Geometry.PolyCurve" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Vector" resolvedName="Autodesk.DesignScript.Geometry.Vector" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="DSCore.List" resolvedName="DSCore.List" assemblyName="DSCoreNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="1c3d7959-3393-481b-a79d-9e85d5789a09" type="PythonNodeModels.PythonNode" nickname="Python Script" x="256" y="1" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>#Copyright (c) mostafa el ayoubi ,  2017
#Data-Shapes www.data-shapes.net , elayoubi.mostafa@gmail.com

import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import*

clr.AddReference('RevitServices')
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

slab = UnwrapElement(IN[0])
sshape = slab.SlabShapeEditor
pts = IN[1]
_reset = IN[2]

UIunit = Document.GetUnits(doc).GetFormatOptions(UnitType.UT_Length).DisplayUnits

TransactionManager.Instance.EnsureInTransaction(doc)
watch = []
if _reset:
	sshape.ResetSlabShape()
	
for i in pts:
	watch.append(sshape.DrawPoint(XYZ(UnitUtils.ConvertToInternalUnits(i.X,UIunit),UnitUtils.ConvertToInternalUnits(i.Y,UIunit),UnitUtils.ConvertToInternalUnits(i.Z,UIunit))))

TransactionManager.Instance.TransactionTaskDone()


OUT = slab</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="a1c1ed2c-df94-4f92-87ce-2462745d7086" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="447" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="OUT" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="54e838a3-e434-41ef-ac0a-ffce59ff3779" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="51.5" y="-66" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Floor element" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="54c8de41-71b2-4203-93df-326e7fe3a9f3" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="23.5" y="34" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Points" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="32410491-0f12-4f95-951a-bc08f8b90a48" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-49.5" y="122" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="ResetSlabShape : bool = false" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="1c3d7959-3393-481b-a79d-9e85d5789a09" start_index="0" end="a1c1ed2c-df94-4f92-87ce-2462745d7086" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="54e838a3-e434-41ef-ac0a-ffce59ff3779" start_index="0" end="1c3d7959-3393-481b-a79d-9e85d5789a09" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="54c8de41-71b2-4203-93df-326e7fe3a9f3" start_index="0" end="1c3d7959-3393-481b-a79d-9e85d5789a09" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="32410491-0f12-4f95-951a-bc08f8b90a48" start_index="0" end="1c3d7959-3393-481b-a79d-9e85d5789a09" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="123.897602500512" eyeY="19.8683153033116" eyeZ="17.90778429543" lookX="-19.2767421228008" lookY="-50.9585112582787" lookZ="37.5256079639917" upX="-0.281315979833602" upY="0.788010753606724" upZ="0.547631602165569" />
  </Cameras>
</Workspace>