<Workspace Version="1.3.3.4111" X="802" Y="196" zoom="1" ScaleFactor="1" Name="ViewSection.ByLine" Description="Create ViewSections in current document from DS Lines. " ID="85cb9075-0c9b-4c2f-a8b7-61d16e1ccc7f" Category="Data-Shapes.Revit.View">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="ce5f10d3-7d34-4df7-aa6c-13ea52fab305" type="PythonNodeModels.PythonNode" nickname="Python Script" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="4">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <PortInfo index="3" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
clr.AddReference('RevitServices')
from RevitServices.Transactions import TransactionManager
from RevitServices.Persistence import DocumentManager
clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.GeometryConversion)


doc = DocumentManager.Instance.CurrentDBDocument


curves = IN[0]
ViewFamilyType = IN[1]
height = IN[2]
offsetFromWall = IN[3]

watch = []

def DSCurveToVewSection(c,vft,offset,doc,height):
	locC = c.ToRevitType()
	sp = locC.GetEndPoint(0)
	ep = locC.GetEndPoint(1)
	v = ep-sp
	w = v.GetLength()
	h = 10
	#ViewSectionBoundingBox
	vsBBmin = XYZ(-w/2-4,sp.Z-1,-offset)
	vsBBmax = XYZ(w/2+4,height + 7,offset)
	midpoint = sp + 0.5*v
	lineDir = v.Normalize()
	up = XYZ.BasisZ
	viewdir = lineDir.CrossProduct(up)
	
	t = Transform.Identity
	t.Origin = midpoint
	t.BasisX = lineDir
	t.BasisY = up
	t.BasisZ = viewdir
	
	vsBB = BoundingBoxXYZ()
	vsBB.Transform = t
	vsBB.Min = vsBBmin
	vsBB.Max = vsBBmax
	
	section = ViewSection.CreateSection(doc,ElementId(vft.Id),vsBB)
	
	return section
	
TransactionManager.Instance.EnsureInTransaction(doc)
watch = [DSCurveToVewSection(c,ViewFamilyType,offsetFromWall,doc,height) for c in curves]
TransactionManager.Instance.TransactionTaskDone

OUT = watch</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="7f2b0010-c60a-4d17-964e-004a0f4106f5" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Curve(s)" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="13b693db-a874-4c9a-a958-5a28db7a9170" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-30" y="96" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="ViewFamilyType" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="a72a0003-fc68-4891-bb48-0bba4df0c9ea" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-52" y="174" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="ViewSection Height" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="1ad595f0-4efb-4834-8171-f76cc556cd77" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-56" y="264" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Offset from Line" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="44be4852-785f-4057-8bb3-60bcc407264f" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="449" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="ViewSection(s)" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="ce5f10d3-7d34-4df7-aa6c-13ea52fab305" start_index="0" end="44be4852-785f-4057-8bb3-60bcc407264f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7f2b0010-c60a-4d17-964e-004a0f4106f5" start_index="0" end="ce5f10d3-7d34-4df7-aa6c-13ea52fab305" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="13b693db-a874-4c9a-a958-5a28db7a9170" start_index="0" end="ce5f10d3-7d34-4df7-aa6c-13ea52fab305" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a72a0003-fc68-4891-bb48-0bba4df0c9ea" start_index="0" end="ce5f10d3-7d34-4df7-aa6c-13ea52fab305" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="1ad595f0-4efb-4834-8171-f76cc556cd77" start_index="0" end="ce5f10d3-7d34-4df7-aa6c-13ea52fab305" end_index="3" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>