<Workspace Version="1.2.0.2690" X="250" Y="230" zoom="1" Name="Grid.SetVerticalExtents" Description="Set the vertical extents of all project grids" ID="f3dfd2d9-68d3-4bab-b7d6-ce9f0c8a02ca" Category="Data-Shapes.Revit.Grids">
  <NamespaceResolutionMap>
    <ClassMap partialName="Category" resolvedName="Revit.Elements.Category" assemblyName="RevitNodes.dll" />
    <ClassMap partialName="Document" resolvedName="Revit.Application.Document" assemblyName="RevitNodes.dll" />
    <ClassMap partialName="String" resolvedName="DSCore.String" assemblyName="DSCoreNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="6ac99795-c856-4b7a-8091-874775edb476" type="PythonNodeModels.PythonNode" nickname="Python Script" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>#Copyright (c) mostafa el ayoubi
#Node-mode www.data-shapes.net 2016 elayoub.mostafa@gmail.com

import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import*
clr.AddReference('RevitServices')
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument
UIunit = Document.GetUnits(doc).GetFormatOptions(UnitType.UT_Length).DisplayUnits

def convunit(x):
	return UnitUtils.ConvertToInternalUnits(x,UIunit)

grids = [UnwrapElement(i) for i in FilteredElementCollector(doc).OfClass(Grid)]

TransactionManager.Instance.EnsureInTransaction(doc)
for g in grids:
	g.SetVerticalExtents(convunit(IN[0]),convunit(IN[1]))
TransactionManager.Instance.TransactionTaskDone()

OUT = grids</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="8a39e062-eab6-41b8-851d-faaabb1b91eb" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="447" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="OUT" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="db64e596-24bd-4207-b5ad-066ace8a639e" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-23.5" y="-39" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Bottom extent" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="dfdf4300-e573-4257-b60c-ce0967d66bae" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-4.5" y="82" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Top extent" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="6ac99795-c856-4b7a-8091-874775edb476" start_index="0" end="8a39e062-eab6-41b8-851d-faaabb1b91eb" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="db64e596-24bd-4207-b5ad-066ace8a639e" start_index="0" end="6ac99795-c856-4b7a-8091-874775edb476" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="dfdf4300-e573-4257-b60c-ce0967d66bae" start_index="0" end="6ac99795-c856-4b7a-8091-874775edb476" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Aperçu en arrière-plan" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>