{
  "Uuid": "3c9d0464-8643-5ffe-96e5-ab1769818209",
  "IsCustomNode": false,
  "Description": "",
  "Name": "Pièces - Centrer le point de référence des pièces",
  "ElementResolver": {
    "ResolutionMap": {
      "Autodesk.Point": {
        "Key": "Autodesk.DesignScript.Geometry.Point",
        "Value": "ProtoGeometry.dll"
      },
      "Autodesk.DesignScript.Geometry.Point": {
        "Key": "Autodesk.DesignScript.Geometry.Point",
        "Value": "ProtoGeometry.dll"
      },
      "DSCore.Image": {
        "Key": "DSCore.IO.Image",
        "Value": "DSCoreNodes.dll"
      },
      "DSCore.IO.Image": {
        "Key": "DSCore.IO.Image",
        "Value": "DSCoreNodes.dll"
      },
      "Geometry.Centroid": {
        "Key": "Autodesk.DesignScript.Geometry.Geometry",
        "Value": "ProtoGeometry.dll"
      }
    }
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Element.SetLocation@Autodesk.DesignScript.Geometry.Geometry",
      "Id": "f7751c658b35460a99bc91ea1c4601f0",
      "Inputs": [
        {
          "Id": "f5a0ca43d7c747c89533d0c2764fe42e",
          "Name": "element",
          "Description": "Revit.Elements.Element",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "cdd3b5d0c3214c93aa6dc5c2fbfe4062",
          "Name": "geometry",
          "Description": "New Location Point or Curve\n\nGeometry",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "e2ed899a3ec24fab88836e0d7d801d9a",
          "Name": "void",
          "Description": "void",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Update an existing element's location\n\nElement.SetLocation (geometry: Geometry): void"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Element.SetLocation@Autodesk.DesignScript.Geometry.Geometry",
      "Id": "1e4227146b324c3fb1a103d2314e39cc",
      "Inputs": [
        {
          "Id": "f1951b9724974dca9cef6138bd007bf1",
          "Name": "element",
          "Description": "Revit.Elements.Element",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "9e535006f4354a0cbeceefaf0b1c06c9",
          "Name": "geometry",
          "Description": "New Location Point or Curve\n\nGeometry",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "7a87e8f39c30405db4a04bdc8af24c5a",
          "Name": "void",
          "Description": "void",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Update an existing element's location\n\nElement.SetLocation (geometry: Geometry): void"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "geo = e.Geometry();\nc = geo.Centroid();",
      "Id": "769e4de466214c32ab42c553605d4585",
      "Inputs": [
        {
          "Id": "8c9a4a95d9734284ad966affbfe231ec",
          "Name": "e",
          "Description": "e",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "458a71bcb2cb4356a1d0d1d640473211",
          "Name": "",
          "Description": "geo",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "bda43a7cc3cb40108ff2bb90a56098bc",
          "Name": "",
          "Description": "c",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "PythonNodeModels.PythonNode, PythonNodeModels",
      "NodeType": "PythonScriptNode",
      "Code": "# Load the Python Standard and DesignScript Libraries\r\nimport sys\r\nimport clr\r\nclr.AddReference('RevitAPI')\r\nfrom Autodesk.Revit.DB import *\r\n\r\nclr.AddReference('RevitServices')\r\nfrom RevitServices.Persistence import DocumentManager\r\ndoc = DocumentManager.Instance.CurrentDBDocument\r\n\r\nrooms = FilteredElementCollector(doc).OfCategory(BuiltInCategory.OST_Rooms).ToElements()\r\n\r\nclosedRooms = [room for room in rooms if room.Area !=0]\r\n\r\nOUT = closedRooms",
      "VariableInputPorts": true,
      "Id": "f2906b63c33d4fa2a0cd594ae4840888",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "24cd3bd113604f989639d8e3cabb7b62",
          "Name": "OUT",
          "Description": "Result of the python script",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Runs an embedded IronPython script."
    }
  ],
  "Connectors": [
    {
      "Start": "bda43a7cc3cb40108ff2bb90a56098bc",
      "End": "9e535006f4354a0cbeceefaf0b1c06c9",
      "Id": "0a0a4539f2274874a61c87f36c59519a"
    },
    {
      "Start": "24cd3bd113604f989639d8e3cabb7b62",
      "End": "8c9a4a95d9734284ad966affbfe231ec",
      "Id": "d5b94134aaec4a5e8cbb4271180f836d"
    },
    {
      "Start": "24cd3bd113604f989639d8e3cabb7b62",
      "End": "f1951b9724974dca9cef6138bd007bf1",
      "Id": "fd5c6aa2f998425590bf6954001aedfc"
    }
  ],
  "Dependencies": [],
  "NodeLibraryDependencies": [],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": true,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.6.1.8786",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -19.361673355102539,
      "EyeY": 38.226512908935547,
      "EyeZ": 0.591814398765564,
      "LookX": 5.7160139083862305,
      "LookY": -33.439468383789063,
      "LookZ": -7.398493766784668,
      "UpX": 0.539816677570343,
      "UpY": 0.46947154402732849,
      "UpZ": -0.69870907068252563
    },
    "NodeViews": [
      {
        "ShowGeometry": true,
        "Name": "Element.SetLocation",
        "Id": "f7751c658b35460a99bc91ea1c4601f0",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 4509.77163776513,
        "Y": -240.055590659977
      },
      {
        "ShowGeometry": true,
        "Name": "Element.SetLocation",
        "Id": "1e4227146b324c3fb1a103d2314e39cc",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -577.28422512519933,
        "Y": -903.76113998835888
      },
      {
        "ShowGeometry": true,
        "Name": "Code Block",
        "Id": "769e4de466214c32ab42c553605d4585",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -844.71289076081791,
        "Y": -819.53445044895989
      },
      {
        "ShowGeometry": true,
        "Name": "Python Script",
        "Id": "f2906b63c33d4fa2a0cd594ae4840888",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -1095.0818156886403,
        "Y": -903.39612163617937
      }
    ],
    "Annotations": [
      {
        "Id": "e1f928e2469e41ccb80b1414ef85301b",
        "Title": "Move the center of the Room",
        "Nodes": [],
        "Left": 4530.49933641681,
        "Top": -285.186055177362,
        "Width": 0.0,
        "Height": 0.0,
        "FontSize": 36.0,
        "InitialTop": 0.0,
        "InitialHeight": 0.0,
        "TextblockHeight": 0.0,
        "Background": "#FFC1D676"
      }
    ],
    "X": 1707.9840543474972,
    "Y": 1420.1872156685172,
    "Zoom": 1.2241601163616436
  }
}